# Generated by Django 4.2.6 on 2023-10-22 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blockauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockauthor',
            name='block_person',
        ),
        migrations.AddField(
            model_name='blockauthor',
            name='blocked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
